---
driver:
  name: vagrant
  require_chef_omnibus: 11.16.2

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[firefox_poise]
    attributes:
