---
driver:
  name: docker
  require_chef_omnibus: latest

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[firefox_package]
    attributes:
