---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    audit_mode: :enabled

platforms:
  - name: ubuntu-14.04
  - name: windows-2012R2
    driver:
      customize:
        usbehci: "off"
    driver_config:
      box_url: https://wrock.blob.core.windows.net/vhds/vbox2012r2.box
      communicator: winrm
      vm_hostname: false
    transport:
      name: winrm

suites:
  - name: default
    run_list:
     - recipe[firefox_package_test]
    attributes:
