sudo: required
services:
  - docker
cache: bundler
language: ruby
bundler_args: "--binstubs"
env:
  global:
  - KITCHEN_LOCAL_YAML=.kitchen.travis.yml
  - DEBIAN_FRONTEND=noninteractive
before_install:
- curl -s https://packagecloud.io/install/repositories/chef/stable/script.deb.sh |
  sudo bash
- sudo apt-get update -qy
install:
- sudo apt-get install -q -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
  chefdk
- sudo chef gem install kitchen-docker-api
script:
- /opt/chefdk/bin/chef exec foodcritic .
- /opt/chefdk/bin/chef exec kitchen test -d never
